<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'residents.view', 'residents.create', 'residents.update', 'residents.delete',
            'units.view', 'units.create', 'units.update', 'units.delete', 'units.convert-property',
            'clusters.view', 'clusters.create', 'clusters.update-rate', 'clusters.delete',
            'cluster-maps.view', 'cluster-maps.edit', 'cluster-map-components.manage',
            'billings.view', 'billings.prepare', 'billings.prepare-special', 'billings.prepare-back', 'billings.approve', 'billings.update', 'billings.delete',
            'billings.waive-penalty', 'billings.approve-penalty-waiver', 'billings.set-discount',
            'penalty-config.view', 'penalty-config.create', 'penalty-config.update', 'penalty-config.delete', 'penalty-config.view-history',
            'discount-config.view', 'discount-config.create', 'discount-config.update', 'discount-config.delete',
            'payments.view', 'payments.create', 'payments.process', 'payments.verify', 'payments.cancel', 'payments.refund',
            'balances.view', 'balances.adjust',
            'installments.view', 'installments.create',
            'reversals.view', 'reversals.submit', 'reversals.approve',
            'reports.view', 'documents.generate',
            'users.view', 'users.create', 'users.update', 'users.delete', 'users.activate', 'users.reset-password',
            'audit-logs.view', 'audit.view',
            'payment-settings.view', 'payment-settings.update',
            'visits.view', 'visits.create', 'visits.update',
            'payment-promises.view', 'payment-promises.create', 'payment-promises.update',
            'resident-documents.view', 'resident-documents.create', 'resident-documents.update', 'resident-documents.delete', 'resident-documents.verify',
            'vehicles.view', 'vehicles.create', 'vehicles.update', 'vehicles.delete',
            'occupants.view', 'occupants.create', 'occupants.update', 'occupants.delete',
            'manual-book.manage', 'help-settings.manage', 'guided-tours.manage',
            'emergency-alerts.view', 'emergency-alerts.acknowledge', 'emergency-alerts.create',
            'landing-cms.manage',
            'collector-assignments.view', 'collector-assignments.create', 'collector-assignments.update', 'collector-assignments.delete', 'collector-assignments.assign',
            'collector-targets.view', 'collector-targets.create', 'collector-targets.update', 'collector-targets.delete',
            'collector-performance.view', 'collector-performance.export', 'collector-performance.print',
            'collector-locations.view',
            'collector-evidence.view', 'collector-evidence.upload', 'collector-evidence.download', 'collector-evidence.delete',
            'collector-complaints.view', 'collector-complaints.approve', 'collector-complaints.reject',
            'collection-letters.view', 'collection-letters.create', 'collection-letters.print', 'collection-letters.download',
            'collector.read', 'collector.create', 'collector.update', 'collector.delete', 'collector.detail',
            'collector.activate', 'collector.assign', 'collector.reassign', 'collector.assignment_history',
            'collector.target_manage', 'collector.location_view',
            'supervisor.view', 'supervisor.create', 'supervisor.update', 'supervisor.delete', 'supervisor.detail', 'supervisor.activate',
            'supervisor-assignments.view', 'supervisor-assignments.assign', 'supervisor-assignments.reassign',
            'collector-monitoring.view',
            'approvals.view', 'approvals.approve', 'approvals.reject',
            'installment-plans.view', 'installment-plans.submit',
            'billing-adjustments.view', 'billing-adjustments.submit',
            'broadcasts.view', 'broadcasts.send',
            'supervisor-notifications.view', 'supervisor-notifications.escalate',
            'reports.export',
            'collector-locations.track',
            'tunggakan-analysis.view',
        ];

        foreach ($permissions as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        $roles = [
            'root' => $permissions,
            'super_admin' => $permissions,
            'admin_estate' => [
                'residents.view', 'residents.create', 'residents.update',
                'units.view', 'units.create', 'units.update', 'units.convert-property',
                'clusters.view', 'clusters.create', 'clusters.update-rate',
                'cluster-maps.view', 'cluster-maps.edit', 'cluster-map-components.manage',
                'billings.view', 'billings.prepare', 'billings.prepare-special', 'billings.prepare-back', 'billings.approve',
                'billings.waive-penalty', 'billings.approve-penalty-waiver', 'billings.set-discount',
                'penalty-config.view', 'penalty-config.create', 'penalty-config.update', 'penalty-config.view-history',
                'discount-config.view', 'discount-config.create', 'discount-config.update',
                'payments.view', 'payments.create', 'payments.verify',
                'balances.view', 'balances.adjust',
                'reports.view', 'documents.generate',
                'users.view', 'users.create', 'users.update', 'users.activate', 'users.reset-password', 'audit-logs.view',
                'payment-settings.view', 'payment-settings.update',
                'visits.view', 'payment-promises.view',
                'resident-documents.view', 'resident-documents.create', 'resident-documents.update', 'resident-documents.delete', 'resident-documents.verify',
                'vehicles.view', 'vehicles.create', 'vehicles.update', 'vehicles.delete',
                'occupants.view', 'occupants.create', 'occupants.update', 'occupants.delete',
                'manual-book.manage',
                'emergency-alerts.view', 'emergency-alerts.acknowledge', 'emergency-alerts.create',
                'landing-cms.manage',
                'collector-assignments.view', 'collector-assignments.create', 'collector-assignments.update', 'collector-assignments.delete', 'collector-assignments.assign',
                'collector-targets.view', 'collector-targets.create', 'collector-targets.update', 'collector-targets.delete',
                'collector-performance.view', 'collector-performance.export', 'collector-performance.print',
                'collector-locations.view',
                'collector-evidence.view', 'collector-evidence.download', 'collector-evidence.delete',
                'collector-complaints.view', 'collector-complaints.approve', 'collector-complaints.reject',
                'collection-letters.view', 'collection-letters.create', 'collection-letters.print', 'collection-letters.download',
                'collector.read', 'collector.create', 'collector.update', 'collector.delete', 'collector.detail',
                'collector.activate', 'collector.assign', 'collector.reassign', 'collector.assignment_history',
                'collector.target_manage', 'collector.location_view',
                'supervisor.view', 'supervisor.create', 'supervisor.update', 'supervisor.delete', 'supervisor.detail', 'supervisor.activate',
                'supervisor-assignments.view', 'supervisor-assignments.assign', 'supervisor-assignments.reassign',
                'collector-monitoring.view',
                'approvals.view', 'approvals.approve', 'approvals.reject',
                'installment-plans.view', 'installment-plans.submit',
                'billing-adjustments.view', 'billing-adjustments.submit',
                'broadcasts.view', 'broadcasts.send',
                'supervisor-notifications.view', 'supervisor-notifications.escalate',
                'reports.export',
                'collector-locations.track',
                'tunggakan-analysis.view',
            ],
            'back_office' => [
                'residents.view', 'residents.create', 'residents.update',
                'units.view', 'units.create', 'units.update', 'units.convert-property',
                'clusters.view', 'clusters.create', 'clusters.update-rate',
                'cluster-maps.view',
                'billings.view', 'billings.prepare', 'billings.prepare-special', 'billings.prepare-back', 'billings.approve', 'billings.update',
                'billings.waive-penalty', 'billings.set-discount',
                'penalty-config.view', 'penalty-config.view-history',
                'discount-config.view',
                'payments.view', 'payments.create', 'payments.process', 'payments.verify',
                'balances.view', 'balances.adjust',
                'installments.view', 'installments.create',
                'installment-plans.view', 'installment-plans.submit',
                'billing-adjustments.view', 'billing-adjustments.submit',
                'reversals.view', 'reversals.submit', 'reversals.approve',
                'reports.view', 'documents.generate',
                'resident-documents.view', 'resident-documents.create',
                'vehicles.view', 'vehicles.create', 'vehicles.update',
                'occupants.view', 'occupants.create', 'occupants.update',
            ],
            'finance' => [
                'residents.view', 'units.view', 'billings.view', 'billings.prepare', 'billings.approve',
                'billings.waive-penalty', 'billings.approve-penalty-waiver', 'billings.set-discount',
                'penalty-config.view', 'penalty-config.view-history',
                'discount-config.view',
                'payments.view', 'payments.create', 'payments.verify', 'payments.refund',
                'balances.view', 'balances.adjust',
                'installments.view', 'installments.create', 'reports.view', 'documents.generate',
                'payment-settings.view',
                'payment-promises.view', 'payment-promises.create', 'payment-promises.update',
                'resident-documents.view', 'resident-documents.verify',
            ],
            'property_manager' => [
                'residents.view', 'units.view', 'clusters.view', 'cluster-maps.view', 'billings.view', 'payments.view',
                'balances.view',
                'reports.view', 'documents.generate', 'users.view',
                'visits.view', 'payment-promises.view',
                'resident-documents.view', 'vehicles.view', 'occupants.view',
                'emergency-alerts.view', 'emergency-alerts.acknowledge',
            ],
            'operations_staff' => ['residents.view', 'units.view', 'clusters.view', 'cluster-maps.view', 'billings.view', 'documents.generate', 'emergency-alerts.view', 'emergency-alerts.acknowledge'],
            'security' => ['residents.view', 'units.view', 'clusters.view', 'cluster-maps.view', 'vehicles.view', 'occupants.view', 'emergency-alerts.view', 'emergency-alerts.acknowledge'],
            'technician' => ['residents.view', 'units.view', 'clusters.view', 'cluster-maps.view'],
            'vendor' => ['residents.view', 'units.view', 'clusters.view', 'cluster-maps.view'],
            'loket' => [
                'residents.view', 'units.view', 'clusters.view', 'cluster-maps.view', 'billings.view',
                'payments.view', 'payments.process', 'payments.create',
                'installments.view', 'installments.create',
                'installment-plans.view', 'installment-plans.submit',
                'reversals.view', 'reversals.submit',
                'documents.generate',
            ],
            'cs' => [
                'residents.view', 'residents.update', 'units.view', 'clusters.view', 'cluster-maps.view', 'billings.view',
                'resident-documents.view', 'resident-documents.create',
                'occupants.view', 'occupants.create', 'occupants.update',
                'emergency-alerts.view', 'emergency-alerts.acknowledge',
            ],
            'collector' => [
                'residents.view', 'units.view', 'clusters.view', 'cluster-maps.view', 'billings.view',
                'payments.view', 'payments.process',
                'visits.view', 'visits.create', 'visits.update',
                'payment-promises.view', 'payment-promises.create', 'payment-promises.update',
                'installments.view',
                'emergency-alerts.create',
                'collector-performance.view',
                'collector-evidence.view', 'collector-evidence.upload',
                'collector-complaints.view',
                'collection-letters.view',
                'collector.detail', 'collector.location_view',
                'installment-plans.view', 'installment-plans.submit',
            ],
            'supervisor' => [
                'residents.view', 'units.view', 'clusters.view', 'cluster-maps.view',
                'billings.view', 'billings.approve-penalty-waiver',
                'payments.view', 'payments.verify',
                'installments.view',
                'installment-plans.view',
                'billing-adjustments.view',
                'reversals.view', 'reversals.approve',
                'reports.view', 'reports.export', 'documents.generate',
                'audit-logs.view',
                'visits.view', 'payment-promises.view',
                'emergency-alerts.view', 'emergency-alerts.acknowledge',
                'collector-assignments.view', 'collector-assignments.assign',
                'collector-targets.view',
                'collector-performance.view', 'collector-performance.export', 'collector-performance.print',
                'collector-locations.view', 'collector-locations.track',
                'collector-evidence.view', 'collector-evidence.download',
                'collector-complaints.view', 'collector-complaints.approve', 'collector-complaints.reject',
                'collection-letters.view', 'collection-letters.create', 'collection-letters.print', 'collection-letters.download',
                'collector.read', 'collector.detail', 'collector.assign', 'collector.reassign',
                'collector.assignment_history', 'collector.location_view',
                'supervisor.detail',
                'supervisor-assignments.view',
                'collector-monitoring.view',
                'approvals.view', 'approvals.approve', 'approvals.reject',
                'broadcasts.view', 'broadcasts.send',
                'supervisor-notifications.view', 'supervisor-notifications.escalate',
                'tunggakan-analysis.view',
            ],
            'customer' => [],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->forceFill(['is_system' => true, 'is_active' => true])->save();
            $role->syncPermissions(Permission::whereIn('name', $rolePermissions)->get());
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
