import { http } from '../api/http.js';

export const storageUrl = (path) => (path ? `${http.defaults.baseURL.replace(/\/api\/v1\/?$/, '')}/storage/${path}` : null);

export const api = {
  auth: {
    login: (payload) => http.post('/auth/login', payload),
    logout: () => http.post('/auth/logout'),
    me: () => http.get('/auth/me'),
    changePassword: (payload) => http.post('/auth/change-password', payload),
  },
  dashboard: {
    summary: () => http.get('/reports/dashboard'),
    monthly: (params) => http.get('/reports/monthly', { params }),
    aging: () => http.get('/receivables/aging'),
  },
  clusters: {
    list: (params) => http.get('/clusters', { params }),
    detail: (id) => http.get(`/clusters/${id}`),
    create: (payload) => http.post('/clusters', payload),
    update: (id, payload) => http.put(`/clusters/${id}`, payload),
    remove: (id) => http.delete(`/clusters/${id}`),
    rateSchedules: (clusterId) => http.get(`/clusters/${clusterId}/rate-schedules`),
    createRateSchedule: (clusterId, payload) => http.post(`/clusters/${clusterId}/rate-schedules`, payload),
    updateRateSchedule: (id, payload) => http.put(`/rate-schedules/${id}`, payload),
    removeRateSchedule: (id) => http.delete(`/rate-schedules/${id}`),
  },
  residents: {
    list: (params) => http.get('/residents', { params }),
    detail: (id) => http.get(`/residents/${id}`),
    create: (payload) => http.post('/residents', payload),
    update: (id, payload) => http.put(`/residents/${id}`, payload),
    remove: (id) => http.delete(`/residents/${id}`),
    checkAvailability: (params) => http.get('/residents/check-availability', { params }),
    summary: (id, params) => http.get(`/residents/${id}/summary`, { params }),
    billings: (id, params) => http.get(`/residents/${id}/billings`, { params }),
    transactions: (id, params) => http.get(`/residents/${id}/transactions`, { params }),
    receipts: (id, params) => http.get(`/residents/${id}/receipts`, { params }),
    sendReceipt: (id, receiptNumber) => http.post(`/residents/${id}/receipts/${receiptNumber}/send`),
    complaints: (id, params) => http.get(`/residents/${id}/complaints`, { params }),
    createComplaint: (id, payload) => http.post(`/residents/${id}/complaints`, payload),
    maintenanceRequests: (id, params) => http.get(`/residents/${id}/maintenance-requests`, { params }),
    createMaintenanceRequest: (id, payload) => http.post(`/residents/${id}/maintenance-requests`, payload),
    notifications: (id, params) => http.get(`/residents/${id}/notifications`, { params }),
    sendNotification: (id, payload) => http.post(`/residents/${id}/notifications/send`, payload),
    activity: (id, params) => http.get(`/residents/${id}/activity`, { params }),
    visits: (id, params) => http.get(`/residents/${id}/visits`, { params }),
    paymentPromises: (id, params) => http.get(`/residents/${id}/payment-promises`, { params }),
    documents: (id, params) => http.get(`/residents/${id}/resident-documents`, { params }),
    createDocument: (id, formData) => http.post(`/residents/${id}/resident-documents`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    vehicles: (id, params) => http.get(`/residents/${id}/vehicles`, { params }),
    occupants: (id, params) => http.get(`/residents/${id}/occupants`, { params }),
  },
  visits: {
    create: (unitId, payload) => http.post(`/units/${unitId}/visits`, payload),
    update: (id, payload) => http.put(`/visits/${id}`, payload),
  },
  paymentPromises: {
    create: (unitId, payload) => http.post(`/units/${unitId}/payment-promises`, payload),
    update: (id, payload) => http.put(`/payment-promises/${id}`, payload),
  },
  residentDocuments: {
    createForUnit: (unitId, formData) => http.post(`/units/${unitId}/resident-documents`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    update: (id, payload) => http.put(`/resident-documents/${id}`, payload),
    remove: (id) => http.delete(`/resident-documents/${id}`),
  },
  vehicles: {
    create: (unitId, payload) => http.post(`/units/${unitId}/vehicles`, payload),
    update: (id, payload) => http.put(`/vehicles/${id}`, payload),
    remove: (id) => http.delete(`/vehicles/${id}`),
  },
  occupants: {
    create: (unitId, payload) => http.post(`/units/${unitId}/occupants`, payload),
    update: (id, payload) => http.put(`/occupants/${id}`, payload),
    remove: (id) => http.delete(`/occupants/${id}`),
  },
  units: {
    list: (params) => http.get('/units', { params }),
    detail: (id) => http.get(`/units/${id}`),
    create: (payload) => http.post('/units', payload),
    update: (id, payload) => http.put(`/units/${id}`, payload),
    remove: (id) => http.delete(`/units/${id}`),
    convert: (id, payload) => http.post(`/units/${id}/convert-property`, payload),
    installments: (id) => http.get(`/units/${id}/installments`),
  },
  billings: {
    list: (params) => http.get('/billings', { params }),
    pendingApproval: (params) => http.get('/billings/pending-approval', { params }),
    prepareMonthly: (payload) => http.post('/billings/prepare-monthly', payload),
    prepareSpecial: (payload) => http.post('/billings/prepare-special', payload),
    prepareBack: (payload) => http.post('/billings/prepare-back', payload),
    approve: (id, payload) => http.post(`/billings/${id}/approve`, payload),
    approveBatch: (payload) => http.post('/billings/approve-batch', payload),
    updateDiscount: (id, payload) => http.put(`/billings/${id}/discount`, payload),
  },
  discountRules: {
    list: (params) => http.get('/discount-rules', { params }),
    create: (payload) => http.post('/discount-rules', payload),
    update: (id, payload) => http.put(`/discount-rules/${id}`, payload),
    remove: (id) => http.delete(`/discount-rules/${id}`),
  },
  payments: {
    search: (params) => http.get('/payments/search', { params }),
    preview: (payload) => http.post('/payments/preview', payload),
    process: (payload) => http.post('/payments/process', payload),
    receipts: (params) => http.get('/payments/receipts', { params }),
    receipt: (number) => http.get(`/payments/receipts/${number}`),
    gatewayConfig: () => http.get('/payments/gateway/config'),
    gatewayTransactions: (params) => http.get('/payments/gateway/transactions', { params }),
    gatewayTransaction: (id) => http.get(`/payments/gateway/transactions/${id}`),
    createGateway: (payload) => http.post('/payments/gateway', payload),
    uploadManualProof: (id, payload) => http.post(`/payments/${id}/manual-proof`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    verifyManual: (id, payload) => http.post(`/payments/${id}/verify`, payload),
    rejectManual: (id, payload) => http.post(`/payments/${id}/reject`, payload),
  },
  resident: {
    dashboard: () => http.get('/resident/dashboard'),
    account: () => http.get('/resident/account'),
    profile: () => http.get('/resident/profile'),
    updateProfile: (payload) => http.post('/resident/profile', payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    property: () => http.get('/resident/property'),
    bills: (params) => http.get('/resident/bills', { params }),
    invoices: (params) => http.get('/resident/invoices', { params }),
    invoice: (id) => http.get(`/resident/invoices/${id}`),
    downloadInvoice: (id) => http.get(`/resident/invoices/${id}/download`, { responseType: 'blob' }),
    createPayment: (invoiceId, payload) => http.post(`/resident/invoices/${invoiceId}/payments`, payload),
    paymentConfig: () => http.get('/resident/payment-config'),
    paymentMethods: () => http.get('/resident/payment-methods'),
    payments: (params) => http.get('/resident/payments', { params }),
    payment: (id) => http.get(`/resident/payments/${id}`),
    paymentStatus: (id) => http.get(`/resident/payments/${id}/status`),
    uploadManualProof: (id, payload) => http.post(`/resident/payments/${id}/manual-proof`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    downloadPaymentReceipt: (id) => http.get(`/resident/payments/${id}/receipt/download`, { responseType: 'blob' }),
    downloadCashReceipt: (number) => http.get(`/resident/receipts/${number}/download`, { responseType: 'blob' }),
    complaints: (params) => http.get('/resident/complaints', { params }),
    complaint: (id) => http.get(`/resident/complaints/${id}`),
    createComplaint: (payload) => http.post('/resident/complaints', payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    updateComplaint: (id, payload) => http.post(`/resident/complaints/${id}`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    addComplaintComment: (id, payload) => http.post(`/resident/complaints/${id}/comments`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    closeComplaint: (id) => http.post(`/resident/complaints/${id}/close`),
    maintenanceRequests: (params) => http.get('/resident/maintenance-requests', { params }),
    maintenanceRequest: (id) => http.get(`/resident/maintenance-requests/${id}`),
    createMaintenanceRequest: (payload) => http.post('/resident/maintenance-requests', payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    updateMaintenanceRequest: (id, payload) => http.post(`/resident/maintenance-requests/${id}`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    rateMaintenanceRequest: (id, payload) => http.post(`/resident/maintenance-requests/${id}/rating`, payload),
    documents: () => http.get('/resident/documents'),
    notifications: (params) => http.get('/resident/notifications', { params }),
    readNotification: (id) => http.post(`/resident/notifications/${id}/read`),
    readAllNotifications: () => http.post('/resident/notifications/read-all'),
    activity: (params) => http.get('/resident/activity', { params }),
    settings: () => http.get('/resident/settings'),
    updateSettings: (payload) => http.put('/resident/settings', payload),
  },
  adminPaymentGateway: {
    show: () => http.get('/admin/settings/payment-gateway'),
    update: (payload) => http.put('/admin/settings/payment-gateway', payload),
    test: () => http.post('/admin/settings/payment-gateway/test'),
  },
  installments: {
    list: (params) => http.get('/installments', { params }),
    create: (payload) => http.post('/installments', payload),
  },
  reversals: {
    list: (params) => http.get('/reversals', { params }),
    create: (payload) => http.post('/reversals', payload),
    approve: (id, payload) => http.post(`/reversals/${id}/approve`, payload),
    reject: (id, payload) => http.post(`/reversals/${id}/reject`, payload),
  },
  receivables: {
    list: (params) => http.get('/receivables', { params }),
    aging: () => http.get('/receivables/aging'),
  },
  reports: {
    monthly: (params) => http.get('/reports/monthly', { params }),
    dailyReceipt: (params) => http.get('/reports/daily-receipt', { params }),
    reconciliation: (params) => http.get('/reports/reconciliation', { params }),
    collector: (params) => http.get('/reports/collector', { params }),
  },
  documents: {
    url: (path) => `${http.defaults.baseURL}${path}`,
  },
  users: {
    list: (params) => http.get('/users', { params }),
    detail: (id) => http.get(`/users/${id}`),
    create: (payload) => http.post('/users', payload),
    update: (id, payload) => http.put(`/users/${id}`, payload),
    remove: (id) => http.delete(`/users/${id}`),
    resetPassword: (id) => http.post(`/users/${id}/reset-password`),
    toggleStatus: (id) => http.post(`/users/${id}/toggle-status`),
    activities: (id, params) => http.get(`/users/${id}/activities`, { params }),
  },
  auditLogs: {
    list: (params) => http.get('/audit-logs', { params }),
  },
  notifications: {
    list: (params) => http.get('/notifications', { params }),
    read: (id) => http.post(`/notifications/${id}/read`),
    readAll: () => http.post('/notifications/read-all'),
  },
  lookup: {
    regencies: () => http.get('/lookup/regencies'),
    districts: (params) => http.get('/lookup/districts', { params }),
    roles: () => http.get('/lookup/roles'),
  },
  manualBook: {
    list: () => http.get('/manual-book/sections'),
    detail: (id) => http.get(`/manual-book/sections/${id}`),
    markRead: (id) => http.post(`/manual-book/sections/${id}/read`),
    adminList: (params) => http.get('/admin/manual-book/sections', { params }),
    adminDetail: (id) => http.get(`/admin/manual-book/sections/${id}`),
    create: (payload) => http.post('/admin/manual-book/sections', payload),
    update: (id, payload) => http.put(`/admin/manual-book/sections/${id}`, payload),
    remove: (id) => http.delete(`/admin/manual-book/sections/${id}`),
    reorder: (ids) => http.post('/admin/manual-book/sections/reorder', { ids }),
    uploadImage: (id, formData) => http.post(`/admin/manual-book/sections/${id}/images`, formData),
    removeImage: (id, imageId) => http.delete(`/admin/manual-book/sections/${id}/images/${imageId}`),
  },
  helpSettings: {
    list: () => http.get('/help-settings'),
    upsert: (settings) => http.put('/admin/help-settings', { settings }),
    remove: (id) => http.delete(`/admin/help-settings/${id}`),
  },
  guidedTours: {
    list: () => http.get('/guided-tours'),
    progress: (id, payload) => http.post(`/guided-tours/${id}/progress`, payload),
    adminList: (params) => http.get('/admin/guided-tours', { params }),
    create: (payload) => http.post('/admin/guided-tours', payload),
    update: (id, payload) => http.put(`/admin/guided-tours/${id}`, payload),
    remove: (id) => http.delete(`/admin/guided-tours/${id}`),
  },
};
