import { http } from '../api/http.js';

export const storageUrl = (path) => (path ? `${http.defaults.baseURL.replace(/\/api\/v1\/?$/, '')}/storage/${path}` : null);

// Every "collection" CMS module (hero slides, services, testimonials, ...) exposes
// the same list/create/update/remove/reorder shape, so build it once per base path
// instead of repeating it ~13 times below.
function makeCollectionApi(basePath) {
  return {
    list: (params) => http.get(basePath, { params }),
    create: (payload) => http.post(basePath, payload),
    update: (id, payload) => http.put(`${basePath}/${id}`, payload),
    remove: (id) => http.delete(`${basePath}/${id}`),
    reorder: (id, direction) => http.post(`${basePath}/${id}/reorder`, { direction }),
  };
}

export const api = {
  auth: {
    login: (payload) => http.post('/auth/login', payload),
    logout: () => http.post('/auth/logout'),
    me: () => http.get('/auth/me'),
    changePassword: (payload) => http.post('/auth/change-password', payload),
  },
  dashboard: {
    summary: () => http.get('/reports/dashboard'),
    monthly: (params) => http.get('/reports/monthly', { params }),
    aging: () => http.get('/receivables/aging'),
  },
  clusters: {
    list: (params) => http.get('/clusters', { params }),
    detail: (id) => http.get(`/clusters/${id}`),
    create: (payload) => http.post('/clusters', payload),
    update: (id, payload) => http.put(`/clusters/${id}`, payload),
    remove: (id) => http.delete(`/clusters/${id}`),
    rateSchedules: (clusterId) => http.get(`/clusters/${clusterId}/rate-schedules`),
    createRateSchedule: (clusterId, payload) => http.post(`/clusters/${clusterId}/rate-schedules`, payload),
    updateRateSchedule: (id, payload) => http.put(`/rate-schedules/${id}`, payload),
    removeRateSchedule: (id) => http.delete(`/rate-schedules/${id}`),
  },
  clusterMaps: {
    get: (clusterId) => http.get(`/clusters/${clusterId}/map`),
    create: (clusterId, payload) => http.post(`/clusters/${clusterId}/map`, payload),
    uploadBackground: (mapId, formData) => http.post(`/cluster-maps/${mapId}/background`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    updateSettings: (mapId, payload) => http.put(`/cluster-maps/${mapId}`, payload),
    saveObjects: (mapId, payload) => http.put(`/cluster-maps/${mapId}/objects`, payload),
    versions: {
      list: (mapId) => http.get(`/cluster-maps/${mapId}/versions`),
      restore: (versionId) => http.post(`/cluster-map-versions/${versionId}/restore`),
    },
  },
  clusterMapComponentTypes: {
    list: () => http.get('/cluster-map-component-types'),
    create: (payload) => http.post('/cluster-map-component-types', payload),
    update: (id, payload) => http.put(`/cluster-map-component-types/${id}`, payload),
    remove: (id) => http.delete(`/cluster-map-component-types/${id}`),
  },
  residents: {
    list: (params) => http.get('/residents', { params }),
    detail: (id) => http.get(`/residents/${id}`),
    create: (payload) => http.post('/residents', payload),
    update: (id, payload) => http.put(`/residents/${id}`, payload),
    remove: (id) => http.delete(`/residents/${id}`),
    checkAvailability: (params) => http.get('/residents/check-availability', { params }),
    summary: (id, params) => http.get(`/residents/${id}/summary`, { params }),
    billings: (id, params) => http.get(`/residents/${id}/billings`, { params }),
    transactions: (id, params) => http.get(`/residents/${id}/transactions`, { params }),
    receipts: (id, params) => http.get(`/residents/${id}/receipts`, { params }),
    sendReceipt: (id, receiptNumber) => http.post(`/residents/${id}/receipts/${receiptNumber}/send`),
    complaints: (id, params) => http.get(`/residents/${id}/complaints`, { params }),
    createComplaint: (id, payload) => http.post(`/residents/${id}/complaints`, payload),
    maintenanceRequests: (id, params) => http.get(`/residents/${id}/maintenance-requests`, { params }),
    createMaintenanceRequest: (id, payload) => http.post(`/residents/${id}/maintenance-requests`, payload),
    notifications: (id, params) => http.get(`/residents/${id}/notifications`, { params }),
    sendNotification: (id, payload) => http.post(`/residents/${id}/notifications/send`, payload),
    activity: (id, params) => http.get(`/residents/${id}/activity`, { params }),
    visits: (id, params) => http.get(`/residents/${id}/visits`, { params }),
    paymentPromises: (id, params) => http.get(`/residents/${id}/payment-promises`, { params }),
    documents: (id, params) => http.get(`/residents/${id}/resident-documents`, { params }),
    createDocument: (id, formData) => http.post(`/residents/${id}/resident-documents`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    vehicles: (id, params) => http.get(`/residents/${id}/vehicles`, { params }),
    occupants: (id, params) => http.get(`/residents/${id}/occupants`, { params }),
  },
  visits: {
    create: (unitId, payload) => http.post(`/units/${unitId}/visits`, payload),
    update: (id, payload) => http.put(`/visits/${id}`, payload),
  },
  paymentPromises: {
    create: (unitId, payload) => http.post(`/units/${unitId}/payment-promises`, payload),
    update: (id, payload) => http.put(`/payment-promises/${id}`, payload),
  },
  residentDocuments: {
    createForUnit: (unitId, formData) => http.post(`/units/${unitId}/resident-documents`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    update: (id, payload) => http.put(`/resident-documents/${id}`, payload),
    remove: (id) => http.delete(`/resident-documents/${id}`),
  },
  vehicles: {
    create: (unitId, payload) => http.post(`/units/${unitId}/vehicles`, payload),
    update: (id, payload) => http.put(`/vehicles/${id}`, payload),
    remove: (id) => http.delete(`/vehicles/${id}`),
  },
  occupants: {
    create: (unitId, payload) => http.post(`/units/${unitId}/occupants`, payload),
    update: (id, payload) => http.put(`/occupants/${id}`, payload),
    remove: (id) => http.delete(`/occupants/${id}`),
  },
  units: {
    list: (params) => http.get('/units', { params }),
    detail: (id) => http.get(`/units/${id}`),
    create: (payload) => http.post('/units', payload),
    update: (id, payload) => http.put(`/units/${id}`, payload),
    remove: (id) => http.delete(`/units/${id}`),
    convert: (id, payload) => http.post(`/units/${id}/convert-property`, payload),
    installments: (id) => http.get(`/units/${id}/installments`),
  },
  billings: {
    list: (params) => http.get('/billings', { params }),
    pendingApproval: (params) => http.get('/billings/pending-approval', { params }),
    prepareMonthly: (payload) => http.post('/billings/prepare-monthly', payload),
    prepareSpecial: (payload) => http.post('/billings/prepare-special', payload),
    prepareBack: (payload) => http.post('/billings/prepare-back', payload),
    approve: (id, payload) => http.post(`/billings/${id}/approve`, payload),
    approveBatch: (payload) => http.post('/billings/approve-batch', payload),
    updateDiscount: (id, payload) => http.put(`/billings/${id}/discount`, payload),
  },
  discountRules: {
    list: (params) => http.get('/discount-rules', { params }),
    create: (payload) => http.post('/discount-rules', payload),
    update: (id, payload) => http.put(`/discount-rules/${id}`, payload),
    remove: (id) => http.delete(`/discount-rules/${id}`),
  },
  payments: {
    search: (params) => http.get('/payments/search', { params }),
    preview: (payload) => http.post('/payments/preview', payload),
    process: (payload) => http.post('/payments/process', payload),
    receipts: (params) => http.get('/payments/receipts', { params }),
    receipt: (number) => http.get(`/payments/receipts/${number}`),
    gatewayConfig: () => http.get('/payments/gateway/config'),
    gatewayTransactions: (params) => http.get('/payments/gateway/transactions', { params }),
    gatewayTransaction: (id) => http.get(`/payments/gateway/transactions/${id}`),
    createGateway: (payload) => http.post('/payments/gateway', payload),
    uploadManualProof: (id, payload) => http.post(`/payments/${id}/manual-proof`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    verifyManual: (id, payload) => http.post(`/payments/${id}/verify`, payload),
    rejectManual: (id, payload) => http.post(`/payments/${id}/reject`, payload),
  },
  resident: {
    dashboard: () => http.get('/resident/dashboard'),
    account: () => http.get('/resident/account'),
    profile: () => http.get('/resident/profile'),
    updateProfile: (payload) => http.post('/resident/profile', payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    property: () => http.get('/resident/property'),
    bills: (params) => http.get('/resident/bills', { params }),
    invoices: (params) => http.get('/resident/invoices', { params }),
    invoice: (id) => http.get(`/resident/invoices/${id}`),
    downloadInvoice: (id) => http.get(`/resident/invoices/${id}/download`, { responseType: 'blob' }),
    createPayment: (invoiceId, payload) => http.post(`/resident/invoices/${invoiceId}/payments`, payload),
    paymentConfig: () => http.get('/resident/payment-config'),
    paymentMethods: () => http.get('/resident/payment-methods'),
    payments: (params) => http.get('/resident/payments', { params }),
    payment: (id) => http.get(`/resident/payments/${id}`),
    paymentStatus: (id) => http.get(`/resident/payments/${id}/status`),
    uploadManualProof: (id, payload) => http.post(`/resident/payments/${id}/manual-proof`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    downloadPaymentReceipt: (id) => http.get(`/resident/payments/${id}/receipt/download`, { responseType: 'blob' }),
    downloadCashReceipt: (number) => http.get(`/resident/receipts/${number}/download`, { responseType: 'blob' }),
    complaints: (params) => http.get('/resident/complaints', { params }),
    complaint: (id) => http.get(`/resident/complaints/${id}`),
    createComplaint: (payload) => http.post('/resident/complaints', payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    updateComplaint: (id, payload) => http.post(`/resident/complaints/${id}`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    addComplaintComment: (id, payload) => http.post(`/resident/complaints/${id}/comments`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    closeComplaint: (id) => http.post(`/resident/complaints/${id}/close`),
    maintenanceRequests: (params) => http.get('/resident/maintenance-requests', { params }),
    maintenanceRequest: (id) => http.get(`/resident/maintenance-requests/${id}`),
    createMaintenanceRequest: (payload) => http.post('/resident/maintenance-requests', payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    updateMaintenanceRequest: (id, payload) => http.post(`/resident/maintenance-requests/${id}`, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }),
    rateMaintenanceRequest: (id, payload) => http.post(`/resident/maintenance-requests/${id}/rating`, payload),
    documents: () => http.get('/resident/documents'),
    notifications: (params) => http.get('/resident/notifications', { params }),
    readNotification: (id) => http.post(`/resident/notifications/${id}/read`),
    readAllNotifications: () => http.post('/resident/notifications/read-all'),
    activity: (params) => http.get('/resident/activity', { params }),
    settings: () => http.get('/resident/settings'),
    updateSettings: (payload) => http.put('/resident/settings', payload),
    tenantInfo: () => http.get('/resident/tenant'),
    createTenant: (payload) => http.post('/resident/tenant', payload),
    updateBillingPayer: (payload) => http.put('/resident/tenant/billing-payer', payload),
    removeTenant: () => http.delete('/resident/tenant'),
  },
  adminPaymentGateway: {
    show: () => http.get('/admin/settings/payment-gateway'),
    update: (payload) => http.put('/admin/settings/payment-gateway', payload),
    test: () => http.post('/admin/settings/payment-gateway/test'),
  },
  installments: {
    list: (params) => http.get('/installments', { params }),
    create: (payload) => http.post('/installments', payload),
  },
  reversals: {
    list: (params) => http.get('/reversals', { params }),
    create: (payload) => http.post('/reversals', payload),
    approve: (id, payload) => http.post(`/reversals/${id}/approve`, payload),
    reject: (id, payload) => http.post(`/reversals/${id}/reject`, payload),
  },
  receivables: {
    list: (params) => http.get('/receivables', { params }),
    aging: () => http.get('/receivables/aging'),
  },
  reports: {
    monthly: (params) => http.get('/reports/monthly', { params }),
    dailyReceipt: (params) => http.get('/reports/daily-receipt', { params }),
    reconciliation: (params) => http.get('/reports/reconciliation', { params }),
    collector: (params) => http.get('/reports/collector', { params }),
  },
  documents: {
    url: (path) => `${http.defaults.baseURL}${path}`,
    billingRecapPdf: (params) => http.get('/documents/billing-recap', { params, responseType: 'blob' }),
    billingRecapExcel: (params) => http.get('/documents/billing-recap-excel', { params, responseType: 'blob' }),
  },
  users: {
    list: (params) => http.get('/users', { params }),
    detail: (id) => http.get(`/users/${id}`),
    create: (payload) => http.post('/users', payload),
    update: (id, payload) => http.put(`/users/${id}`, payload),
    remove: (id) => http.delete(`/users/${id}`),
    resetPassword: (id) => http.post(`/users/${id}/reset-password`),
    toggleStatus: (id) => http.post(`/users/${id}/toggle-status`),
    activities: (id, params) => http.get(`/users/${id}/activities`, { params }),
  },
  auditLogs: {
    list: (params) => http.get('/audit-logs', { params }),
  },
  notifications: {
    list: (params) => http.get('/notifications', { params }),
    read: (id) => http.post(`/notifications/${id}/read`),
    readAll: () => http.post('/notifications/read-all'),
  },
  emergencyAlerts: {
    list: (params) => http.get('/emergency-alerts', { params }),
    create: (payload) => http.post('/emergency-alerts', payload),
    acknowledge: (id) => http.post(`/emergency-alerts/${id}/acknowledge`),
  },
  lookup: {
    regencies: () => http.get('/lookup/regencies'),
    districts: (params) => http.get('/lookup/districts', { params }),
    roles: () => http.get('/lookup/roles'),
  },
  manualBook: {
    list: () => http.get('/manual-book/sections'),
    detail: (id) => http.get(`/manual-book/sections/${id}`),
    markRead: (id) => http.post(`/manual-book/sections/${id}/read`),
    adminList: (params) => http.get('/admin/manual-book/sections', { params }),
    adminDetail: (id) => http.get(`/admin/manual-book/sections/${id}`),
    create: (payload) => http.post('/admin/manual-book/sections', payload),
    update: (id, payload) => http.put(`/admin/manual-book/sections/${id}`, payload),
    remove: (id) => http.delete(`/admin/manual-book/sections/${id}`),
    reorder: (ids) => http.post('/admin/manual-book/sections/reorder', { ids }),
    uploadImage: (id, formData) => http.post(`/admin/manual-book/sections/${id}/images`, formData),
    removeImage: (id, imageId) => http.delete(`/admin/manual-book/sections/${id}/images/${imageId}`),
  },
  helpSettings: {
    list: () => http.get('/help-settings'),
    upsert: (settings) => http.put('/admin/help-settings', { settings }),
    remove: (id) => http.delete(`/admin/help-settings/${id}`),
  },
  guidedTours: {
    list: () => http.get('/guided-tours'),
    progress: (id, payload) => http.post(`/guided-tours/${id}/progress`, payload),
    adminList: (params) => http.get('/admin/guided-tours', { params }),
    create: (payload) => http.post('/admin/guided-tours', payload),
    update: (id, payload) => http.put(`/admin/guided-tours/${id}`, payload),
    remove: (id) => http.delete(`/admin/guided-tours/${id}`),
  },
  landing: {
    content: () => http.get('/landing/content'),
    article: (slug) => http.get(`/landing/articles/${slug}`),
    event: (slug) => http.get(`/landing/events/${slug}`),
  },
  cms: {
    media: {
      list: (params) => http.get('/cms/media', { params }),
      upload: (formData) => http.post('/cms/media', formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
      remove: (id) => http.delete(`/cms/media/${id}`),
    },
    heroSlides: makeCollectionApi('/cms/hero-slides'),
    services: makeCollectionApi('/cms/services'),
    features: makeCollectionApi('/cms/features'),
    statistics: makeCollectionApi('/cms/statistics'),
    testimonials: makeCollectionApi('/cms/testimonials'),
    partners: makeCollectionApi('/cms/partners'),
    faqs: makeCollectionApi('/cms/faqs'),
    categories: makeCollectionApi('/cms/categories'),
    navMenuItems: makeCollectionApi('/cms/nav-menu-items'),
    socialLinks: makeCollectionApi('/cms/social-links'),
    events: makeCollectionApi('/cms/events'),
    articles: makeCollectionApi('/cms/articles'),
    galleryAlbums: {
      ...makeCollectionApi('/cms/gallery-albums'),
      items: {
        list: (albumId) => http.get(`/cms/gallery-albums/${albumId}/items`),
        create: (albumId, payload) => http.post(`/cms/gallery-albums/${albumId}/items`, payload),
        update: (id, payload) => http.put(`/cms/gallery-items/${id}`, payload),
        remove: (id) => http.delete(`/cms/gallery-items/${id}`),
        reorder: (id, direction) => http.post(`/cms/gallery-items/${id}/reorder`, { direction }),
      },
    },
    settings: {
      header: { show: () => http.get('/cms/settings/header'), update: (payload) => http.put('/cms/settings/header', payload) },
      about: { show: () => http.get('/cms/settings/about'), update: (payload) => http.put('/cms/settings/about', payload) },
      contact: { show: () => http.get('/cms/settings/contact'), update: (payload) => http.put('/cms/settings/contact', payload) },
      footer: { show: () => http.get('/cms/settings/footer'), update: (payload) => http.put('/cms/settings/footer', payload) },
      seo: { show: () => http.get('/cms/settings/seo'), update: (payload) => http.put('/cms/settings/seo', payload) },
      general: { show: () => http.get('/cms/settings/general'), update: (payload) => http.put('/cms/settings/general', payload) },
    },
  },
  collectors: {
    list: (params) => http.get('/collectors', { params }),
    create: (payload) => http.post('/collectors', payload),
    update: (id, payload) => http.put(`/collectors/${id}`, payload),
    remove: (id) => http.delete(`/collectors/${id}`),
    detail: (id) => http.get(`/collectors/${id}`),
    updateStatus: (id, payload) => http.patch(`/collectors/${id}/status`, payload),
    assignmentHistory: (id, params) => http.get(`/collectors/${id}/assignment-history`, { params }),
    uploadPhoto: (id, formData) => http.post(`/collectors/${id}/photo`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  },
  collectorAssignments: {
    list: (params) => http.get('/collector-assignments', { params }),
    create: (payload) => http.post('/collector-assignments', payload),
    update: (id, payload) => http.put(`/collector-assignments/${id}`, payload),
    remove: (id) => http.delete(`/collector-assignments/${id}`),
    reassign: (id, payload) => http.post(`/collector-assignments/${id}/reassign`, payload),
  },
  collectorTargets: {
    list: (params) => http.get('/collector-targets', { params }),
    create: (payload) => http.post('/collector-targets', payload),
    update: (id, payload) => http.put(`/collector-targets/${id}`, payload),
    remove: (id) => http.delete(`/collector-targets/${id}`),
  },
  collectorPerformance: {
    forCollector: (params) => http.get('/collector-performance', { params }),
    mine: (params) => http.get('/collector-performance/me', { params }),
  },
  collectorLocations: {
    send: (payload) => http.post('/collector-locations', payload),
    list: (params) => http.get('/collector-locations', { params }),
    latest: () => http.get('/collector-locations/latest'),
  },
  visitEvidence: {
    list: (visitId) => http.get(`/visits/${visitId}/evidence`),
    upload: (visitId, formData) => http.post(`/visits/${visitId}/evidence`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
    remove: (id) => http.delete(`/visit-evidence/${id}`),
  },
  collectionLetters: {
    list: (params) => http.get('/collection-letters', { params }),
    create: (payload) => http.post('/collection-letters', payload),
    download: (id) => http.get(`/collection-letters/${id}/download`, { responseType: 'blob' }),
  },
  collectorReminders: {
    list: (params) => http.get('/collector-reminders', { params }),
    create: (payload) => http.post('/collector-reminders', payload),
  },
  supervisors: {
    list: (params) => http.get('/supervisors', { params }),
    create: (payload) => http.post('/supervisors', payload),
    update: (id, payload) => http.put(`/supervisors/${id}`, payload),
    remove: (id) => http.delete(`/supervisors/${id}`),
    detail: (id) => http.get(`/supervisors/${id}`),
    updateStatus: (id, payload) => http.patch(`/supervisors/${id}/status`, payload),
    activityHistory: (id, params) => http.get(`/supervisors/${id}/activity-history`, { params }),
    uploadPhoto: (id, formData) => http.post(`/supervisors/${id}/photo`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  },
  supervisorAssignments: {
    list: (params) => http.get('/supervisor-assignments', { params }),
    create: (payload) => http.post('/supervisor-assignments', payload),
    update: (id, payload) => http.put(`/supervisor-assignments/${id}`, payload),
    remove: (id) => http.delete(`/supervisor-assignments/${id}`),
    reassign: (id, payload) => http.post(`/supervisor-assignments/${id}/reassign`, payload),
  },
  supervisorDashboard: {
    summary: () => http.get('/supervisor/dashboard'),
  },
  supervisorMonitoring: {
    collectors: (params) => http.get('/supervisor/collectors', { params }),
    collectorDetail: (id) => http.get(`/supervisor/collectors/${id}`),
    targets: (params) => http.get('/supervisor/targets', { params }),
    paymentPromises: (params) => http.get('/supervisor/payment-promises', { params }),
    payments: (params) => http.get('/supervisor/payments', { params }),
    map: () => http.get('/supervisor/map'),
  },
  tunggakan: {
    clusters: () => http.get('/supervisor/tunggakan'),
    detail: (clusterId) => http.get(`/supervisor/tunggakan/${clusterId}`),
  },
  approvals: {
    list: (params) => http.get('/approval-requests', { params }),
    detail: (id) => http.get(`/approval-requests/${id}`),
    submitInstallmentPlan: (payload) => http.post('/approval-requests/installment-plans', payload),
    submitBillingAdjustment: (payload) => http.post('/approval-requests/billing-adjustments', payload),
    approve: (id, payload) => http.post(`/approval-requests/${id}/approve`, payload),
    reject: (id, payload) => http.post(`/approval-requests/${id}/reject`, payload),
    uploadDocument: (id, formData) => http.post(`/approval-requests/${id}/documents`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  },
  supervisorNotifications: {
    list: (params) => http.get('/supervisor-notifications', { params }),
    markRead: (id) => http.post(`/supervisor-notifications/${id}/read`),
    markHandled: (id) => http.post(`/supervisor-notifications/${id}/handled`),
    escalate: (id, payload) => http.post(`/supervisor-notifications/${id}/escalate`, payload),
  },
  broadcasts: {
    list: (params) => http.get('/broadcasts', { params }),
    detail: (id) => http.get(`/broadcasts/${id}`),
    send: (payload) => http.post('/broadcasts', payload),
  },
  reportExports: {
    list: (params) => http.get('/report-exports', { params }),
    create: (payload) => http.post('/report-exports', payload),
    detail: (id) => http.get(`/report-exports/${id}`),
    download: (id) => http.get(`/report-exports/${id}/download`, { responseType: 'blob' }),
  },
};
