import {
  AuditOutlined,
  BankOutlined,
  BellOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  HistoryOutlined,
  HomeOutlined,
  ProfileOutlined,
  ReconciliationOutlined,
  SettingOutlined,
  TeamOutlined,
  UserOutlined,
  WalletOutlined,
  ToolOutlined,
  SafetyCertificateOutlined,
} from '@ant-design/icons';

export const roles = ['root', 'back_office', 'loket', 'cs', 'customer'];

export const menuItems = [
  { key: '/', label: 'Dashboard', icon: DashboardOutlined, permissions: ['reports.view', 'customers.view', 'billings.view'] },
  { key: '/clusters', label: 'Cluster', icon: HomeOutlined, permissions: ['clusters.view'] },
  { key: '/customers', label: 'Pelanggan', icon: BankOutlined, permissions: ['customers.view'] },
  { key: '/billings', label: 'Tagihan', icon: FileTextOutlined, permissions: ['billings.view'] },
  { key: '/payments', label: 'Pembayaran', icon: CreditCardOutlined, permissions: ['payments.view'] },
  { key: '/installments', label: 'Cicilan', icon: WalletOutlined, permissions: ['installments.view'] },
  { key: '/reversals', label: 'Reversal', icon: HistoryOutlined, permissions: ['reversals.view'] },
  { key: '/receivables', label: 'Piutang', icon: ReconciliationOutlined, permissions: ['reports.view'] },
  { key: '/reports', label: 'Laporan', icon: ProfileOutlined, permissions: ['reports.view'] },
  { key: '/documents', label: 'Dokumen PDF', icon: FolderOpenOutlined, permissions: ['documents.generate'] },
  { key: '/users', label: 'User', icon: TeamOutlined, permissions: ['users.view'] },
  { key: '/audit-logs', label: 'Audit Log', icon: AuditOutlined, permissions: ['audit-logs.view'] },
  { key: '/admin/settings/payment-gateway', label: 'Payment Gateway', icon: SafetyCertificateOutlined, permissions: ['payment-settings.view'] },
  { key: '/notifications', label: 'Notifikasi', icon: BellOutlined, permissions: [], roles: ['root', 'back_office', 'loket', 'cs'] },
  { key: '/profile', label: 'Profil', icon: UserOutlined, permissions: [], roles: ['root', 'back_office', 'loket', 'cs'] },
  { key: '/change-password', label: 'Ganti Password', icon: FileDoneOutlined, permissions: [], roles: ['root', 'back_office', 'loket', 'cs'] },
  { key: '/customer/dashboard', label: 'Dashboard Customer', icon: DashboardOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/account', label: 'Akun', icon: UserOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/property', label: 'Properti', icon: HomeOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/bills', label: 'Tagihan', icon: FileTextOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/payments', label: 'Pembayaran', icon: CreditCardOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/payment-methods', label: 'Metode Bayar', icon: WalletOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/complaints', label: 'Komplain', icon: BellOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/maintenance-requests', label: 'Maintenance', icon: ToolOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/documents', label: 'Dokumen', icon: FolderOpenOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/notifications', label: 'Notifikasi', icon: BellOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/activity', label: 'Aktivitas', icon: AuditOutlined, permissions: [], roles: ['customer'] },
  { key: '/customer/settings', label: 'Pengaturan', icon: SettingOutlined, permissions: [], roles: ['customer'] },
];

export const permissionLabels = {
  'customers.view': 'Lihat pelanggan',
  'customers.create': 'Tambah pelanggan',
  'customers.update': 'Edit pelanggan',
  'customers.delete': 'Hapus pelanggan',
  'customers.convert-property': 'Konversi properti',
  'clusters.view': 'Lihat cluster',
  'clusters.create': 'Tambah cluster',
  'clusters.update-rate': 'Edit tarif cluster',
  'clusters.delete': 'Hapus cluster',
  'billings.view': 'Lihat tagihan',
  'billings.prepare': 'Generate tagihan',
  'billings.prepare-special': 'Tagihan khusus',
  'billings.prepare-back': 'Tagihan mundur',
  'billings.approve': 'Approve tagihan',
  'payments.view': 'Lihat pembayaran',
  'payments.process': 'Proses loket',
  'payments.create': 'Buat transaksi gateway',
  'payments.verify': 'Verifikasi manual',
  'users.view': 'Lihat user',
  'users.create': 'Tambah user',
  'users.update': 'Edit user',
  'users.delete': 'Hapus user',
  'users.activate': 'Aktivasi user',
  'users.reset-password': 'Reset password',
  'audit-logs.view': 'Audit log',
  'reports.view': 'Laporan',
  'documents.generate': 'Generate dokumen',
  'payment-settings.view': 'Lihat pengaturan payment gateway',
  'payment-settings.update': 'Ubah pengaturan payment gateway',
};
