import {
  ApartmentOutlined,
  AuditOutlined,
  BankOutlined,
  BellOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  HistoryOutlined,
  HomeOutlined,
  ProfileOutlined,
  ReconciliationOutlined,
  SettingOutlined,
  TeamOutlined,
  UserOutlined,
  WalletOutlined,
  ToolOutlined,
  SafetyCertificateOutlined,
  ReadOutlined,
} from '@ant-design/icons';

export const roles = ['root', 'back_office', 'loket', 'cs', 'customer'];

export const menuItems = [
  { key: '/', label: 'Dashboard', icon: DashboardOutlined, permissions: ['reports.view', 'residents.view', 'billings.view'] },
  { key: '/manual-book', label: 'Manual Book', icon: ReadOutlined, permissions: [] },
  { key: '/clusters', label: 'Cluster', icon: HomeOutlined, permissions: ['clusters.view'] },
  { key: '/residents', label: 'Penghuni', icon: BankOutlined, permissions: ['residents.view'] },
  { key: '/units', label: 'Unit Rumah', icon: ApartmentOutlined, permissions: ['units.view'] },
  { key: '/billings', label: 'Tagihan', icon: FileTextOutlined, permissions: ['billings.view'] },
  { key: '/payments', label: 'Pembayaran', icon: CreditCardOutlined, permissions: ['payments.view'] },
  { key: '/installments', label: 'Cicilan', icon: WalletOutlined, permissions: ['installments.view'] },
  { key: '/reversals', label: 'Reversal', icon: HistoryOutlined, permissions: ['reversals.view'] },
  { key: '/receivables', label: 'Piutang', icon: ReconciliationOutlined, permissions: ['reports.view'] },
  { key: '/reports', label: 'Laporan', icon: ProfileOutlined, permissions: ['reports.view'] },
  { key: '/documents', label: 'Dokumen PDF', icon: FolderOpenOutlined, permissions: ['documents.generate'] },
  { key: '/users', label: 'User', icon: TeamOutlined, permissions: ['users.view'] },
  { key: '/audit-logs', label: 'Audit Log', icon: AuditOutlined, permissions: ['audit-logs.view'] },
  { key: '/admin/settings/payment-gateway', label: 'Payment Gateway', icon: SafetyCertificateOutlined, permissions: ['payment-settings.view'] },
  { key: '/admin/manual-book', label: 'Kelola Manual Book', icon: ReadOutlined, permissions: ['manual-book.manage'] },
  { key: '/admin/help-settings', label: 'Pengaturan Bantuan', icon: SettingOutlined, permissions: ['help-settings.manage'] },
  { key: '/notifications', label: 'Notifikasi', icon: BellOutlined, permissions: [], roles: ['root', 'back_office', 'loket', 'cs'] },
  { key: '/profile', label: 'Profil', icon: UserOutlined, permissions: [], roles: ['root', 'back_office', 'loket', 'cs'] },
  { key: '/change-password', label: 'Ganti Password', icon: FileDoneOutlined, permissions: [], roles: ['root', 'back_office', 'loket', 'cs'] },
  { key: '/resident/dashboard', label: 'Dashboard Penghuni', icon: DashboardOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/account', label: 'Akun', icon: UserOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/property', label: 'Properti', icon: HomeOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/bills', label: 'Tagihan', icon: FileTextOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/payments', label: 'Pembayaran', icon: CreditCardOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/payment-methods', label: 'Metode Bayar', icon: WalletOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/complaints', label: 'Komplain', icon: BellOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/maintenance-requests', label: 'Maintenance', icon: ToolOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/documents', label: 'Dokumen', icon: FolderOpenOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/notifications', label: 'Notifikasi', icon: BellOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/activity', label: 'Aktivitas', icon: AuditOutlined, permissions: [], roles: ['customer'] },
  { key: '/resident/settings', label: 'Pengaturan', icon: SettingOutlined, permissions: [], roles: ['customer'] },
];

export const permissionLabels = {
  'residents.view': 'Lihat penghuni',
  'residents.create': 'Tambah penghuni',
  'residents.update': 'Edit penghuni',
  'residents.delete': 'Hapus penghuni',
  'units.view': 'Lihat unit',
  'units.create': 'Tambah unit',
  'units.update': 'Edit unit',
  'units.delete': 'Hapus unit',
  'units.convert-property': 'Konversi properti unit',
  'clusters.view': 'Lihat cluster',
  'clusters.create': 'Tambah cluster',
  'clusters.update-rate': 'Edit tarif cluster',
  'clusters.delete': 'Hapus cluster',
  'cluster-maps.view': 'Lihat peta cluster',
  'cluster-maps.edit': 'Edit peta cluster',
  'cluster-map-components.manage': 'Kelola komponen peta cluster',
  'billings.view': 'Lihat tagihan',
  'billings.prepare': 'Generate tagihan',
  'billings.prepare-special': 'Tagihan khusus',
  'billings.prepare-back': 'Tagihan mundur',
  'billings.approve': 'Approve tagihan',
  'billings.set-discount': 'Atur diskon tagihan',
  'billings.waive-penalty': 'Ajukan keringanan denda',
  'billings.approve-penalty-waiver': 'Setujui keringanan denda',
  'penalty-config.view': 'Lihat aturan denda',
  'penalty-config.create': 'Tambah aturan denda',
  'penalty-config.update': 'Edit aturan denda',
  'penalty-config.delete': 'Hapus aturan denda',
  'penalty-config.view-history': 'Lihat riwayat aturan denda',
  'discount-config.view': 'Lihat aturan diskon',
  'discount-config.create': 'Tambah aturan diskon',
  'discount-config.update': 'Edit aturan diskon',
  'discount-config.delete': 'Hapus aturan diskon',
  'payments.view': 'Lihat pembayaran',
  'payments.process': 'Proses loket',
  'payments.create': 'Buat transaksi gateway',
  'payments.verify': 'Verifikasi manual',
  'users.view': 'Lihat user',
  'users.create': 'Tambah user',
  'users.update': 'Edit user',
  'users.delete': 'Hapus user',
  'users.activate': 'Aktivasi user',
  'users.reset-password': 'Reset password',
  'audit-logs.view': 'Audit log',
  'reports.view': 'Laporan',
  'documents.generate': 'Generate dokumen',
  'payment-settings.view': 'Lihat pengaturan payment gateway',
  'payment-settings.update': 'Ubah pengaturan payment gateway',
  'manual-book.manage': 'Kelola Manual Book',
  'help-settings.manage': 'Kelola pengaturan ikon bantuan',
  'guided-tours.manage': 'Kelola Guided Tour',
};
